// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.5
// source: proto/repos.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ReposServiceClient is the client API for ReposService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ReposServiceClient interface {
	GetRepos(ctx context.Context, in *RepoRequest, opts ...grpc.CallOption) (*RepoResponse, error)
}

type reposServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewReposServiceClient(cc grpc.ClientConnInterface) ReposServiceClient {
	return &reposServiceClient{cc}
}

func (c *reposServiceClient) GetRepos(ctx context.Context, in *RepoRequest, opts ...grpc.CallOption) (*RepoResponse, error) {
	out := new(RepoResponse)
	err := c.cc.Invoke(ctx, "/ReposService/GetRepos", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ReposServiceServer is the server API for ReposService service.
// All implementations must embed UnimplementedReposServiceServer
// for forward compatibility
type ReposServiceServer interface {
	GetRepos(context.Context, *RepoRequest) (*RepoResponse, error)
	mustEmbedUnimplementedReposServiceServer()
}

// UnimplementedReposServiceServer must be embedded to have forward compatible implementations.
type UnimplementedReposServiceServer struct {
}

func (UnimplementedReposServiceServer) GetRepos(context.Context, *RepoRequest) (*RepoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRepos not implemented")
}
func (UnimplementedReposServiceServer) mustEmbedUnimplementedReposServiceServer() {}

// UnsafeReposServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ReposServiceServer will
// result in compilation errors.
type UnsafeReposServiceServer interface {
	mustEmbedUnimplementedReposServiceServer()
}

func RegisterReposServiceServer(s grpc.ServiceRegistrar, srv ReposServiceServer) {
	s.RegisterService(&ReposService_ServiceDesc, srv)
}

func _ReposService_GetRepos_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RepoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReposServiceServer).GetRepos(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ReposService/GetRepos",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReposServiceServer).GetRepos(ctx, req.(*RepoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ReposService_ServiceDesc is the grpc.ServiceDesc for ReposService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ReposService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ReposService",
	HandlerType: (*ReposServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetRepos",
			Handler:    _ReposService_GetRepos_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/repos.proto",
}
